.gitignore
entity_gym/entity_gym/environment.py
entity_gym/entity_gym/envs/move_to_origin.py
entity_gym/setup.py
ppo/requirements.txt
ppo/train.py

It is extremely slow, and unclear if it manages to learn anything, but runs without crashing: https://wandb.ai/cswinter/enn-ppo/runs/1qsbkteg
Fixes https://github.com/entity-neural-network/incubator/issues/4 and https://github.com/entity-neural-network/incubator/issues/3

Adapt CleanRL ppo implementation

---

entity_gym/entity_gym/environment.py
entity_gym/entity_gym/envs/minefield.py
ppo/README.md
ppo/requirements.txt
ppo/train.py

30x speedup by batching forward passes.

Batch forward passes

---

.gitignore
entity_gym/entity_gym/environment.py
entity_gym/entity_gym/envs/__init__.py
entity_gym/entity_gym/envs/cherry_pick.py
entity_gym/entity_gym/envs/move_to_origin.py
entity_gym/entity_gym/envs/multi_armed_bandit.py
entity_gym/entity_gym/envs/multi_snake.py
entity_gym/entity_gym/envs/pick_matching_balls.py
entity_gym/entity_gym/main.py
mypy.ini
ppo/train.py

The obs/logprob/action buffers weren't getting reset and kept accumulating which broke training.
With this fixed, we can now solve the new MultiArmedBandit and MoveToOrigin environments:
- https://wandb.ai/cswinter/enn-ppo/runs/3vkeo0mr?workspace=user-cswinter
- https://wandb.ai/cswinter/enn-ppo/runs/3btl2u0y?workspace=user-cswinter
Fixes https://github.com/entity-neural-network/incubator/issues/13

Fix PPO, MultiArmedBandit env, small improvements

---

.github/workflows/tests.yaml
CONTRIBUTING.md
requirements-dev.txt

Fixes https://github.com/entity-neural-network/incubator/issues/36

Add CONTRIBUTING.md

---

rogue_net/requirements.txt
rogue_net/rogue_net/input_norm.py
rogue_net/rogue_net/test_input_norm.py

Moved `InputNorm` layer to the **RogueNet** package, I did not delete the old one.
I added `freeze` and `unfreeze` methods, according to #25, a test for the cliprange and a test for the new methods.

Move InputNorm to RogueNet and add methods for #25

---

enn_ppo/requirements.txt
enn_ppo/setup.py
rogue_net/requirements.txt
rogue_net/setup.py

Increases compatibility with other packages.

Relax dependency version ranges

---

enn_ppo/enn_ppo/train.py
enn_ppo/pyproject.toml
entity_gym/pyproject.toml
poetry.lock
pyproject.toml
rogue_net/pyproject.toml
rogue_net/rogue_net/actor.py

This shaves off another 350ms from each iteration when running `MultiArmedBandit` with 64, increasing throughput by > 50%.
Before/after comparison: https://wandb.ai/entity-neural-network/enn-ppo/reports/Ragged-tensor-metadata-optimization--VmlldzoxMjkxMTQ2

Push ragged tensor metadata creation into Rust

---

enn_ppo/enn_ppo/train.py

The episodic_return and length metrics was biased towards environments at a low index of the `VecEnv`, which can cause large systematic error in cases where parallel environments are not identical. This is fixed by averaging returns and lengths. Performance impact is minimal, even in cases where episodes only last one timestep.

Fix bias in episodic_return metric

---

enn_ppo/enn_ppo/train.py

This PR fixes #95 with an alternative method that does not use averaging like #93

Alternative fix to bias with the episodic return logging

---

enn_ppo/enn_ppo/test_training.py
enn_ppo/enn_ppo/train.py
entity_gym/entity_gym/dataclass_utils.py
entity_gym/entity_gym/envs/__init__.py
entity_gym/entity_gym/envs/count.py
entity_gym/entity_gym/envs/not_hotdog.py
entity_gym/entity_gym/envs/xor.py

Two new simple environments to test multiple entity types, variable number of entities on each timestep, and required mixing of information across entitites.

Add simple Xor and Count environments

---

enn_ppo/enn_ppo/test_training.py
enn_ppo/enn_ppo/train.py
entity_gym/entity_gym/envs/multi_snake.py

Improvement to https://github.com/entity-neural-network/incubator/issues/98.

Compute episodic_return as average over entire rollout

---

requirements-dev.txt

This is out of date and is handled by poetry now.

Remove requirements-dev.txt

---

enn_ppo/enn_ppo/train.py
entity_gym/entity_gym/envs/pick_matching_balls.py

Several small changes that make the PickMatchingBalls environment slightly easier to solve:
- Add entropy annealing
- Add `randomize` arg to randomize the initial number of balls
- Add `one_hot` arg to one-hot encode the color feature

Parameterize PickMatchingBalls and add entropy annealing

---

entity_gym/entity_gym/envs/multi_snake.py

The fix in https://github.com/entity-neural-network/incubator/pull/125 introduced a new bug that prevents policies from attaining the maximum score.

Fix MultiSnake max score bug

---

enn_ppo/pyproject.toml
entity_gym/pyproject.toml
poetry.lock
rogue_net/pyproject.toml
rogue_net/rogue_net/actor.py
rogue_net/rogue_net/translate_positions.py

Translation layer was mutating the (first batch) of the sample buffer, causing the translation to be applied a second time to some datapoints during optimization.

Fix bug in translation layer

---

enn_ppo/enn_ppo/train.py

Adds a new `--microbatch-size` arg to train.py that enables larger batch sizes by accumulating gradients for a single minibatch over multiple microbatches.

Implement gradient accumulation

---

.github/workflows/tests.yaml
CONTRIBUTING.md
enn_ppo/poetry.lock
enn_ppo/pyproject.toml
poetry.lock
pyproject.toml
rogue_net/poetry.lock
rogue_net/pyproject.toml

Poetry: stop fighting with cuda dependencies

---

.github/workflows/black.yaml
.github/workflows/mypy.yaml

Split mypy, black, and tests into 3 separate actions

---

enn_ppo/enn_ppo/hypertuna.py
xprun/train.ron

Makes several improvements to hypertuna.py:
- run different number of experiments per trial depending on how likely it is that the trial will beat the best previous result
- add support for n-head hyperparameter
- add max-microbatch-size arg
- update xprun config with new build process
- misc fixes

Hypertuner adaptive number of runs

---

enn_ppo/enn_ppo/train.py
entity_gym/entity_gym/examples/not_hotdog.py
rogue_net/rogue_net/head_creator.py
rogue_net/rogue_net/tests/test_action_head.py

Fixes https://github.com/entity-neural-network/incubator/issues/159

Fix crash when action has 0 actors

---

enn_zoo/enn_zoo/griddly/__init__.py
enn_zoo/enn_zoo/griddly/test_griddly_env.py
poetry.lock
pyproject.toml

Another small fix for Griddly to produce rotation unit vectors for envs

adding object orientation vectors to test

---

enn_ppo/enn_ppo/train.py

Closes the eval environments at the end of running evals, and fixes missing arguments on the final eval.

Close envs at end of eval and fix final eval

---

enn_ppo/README.md
enn_ppo/enn_ppo/supervised.py
enn_ppo/enn_ppo/train.py
enn_ppo/poetry.lock
enn_ppo/pyproject.toml
enn_zoo/poetry.lock
enn_zoo/pyproject.toml
poetry.lock
rogue_net/rogue_net/actor.py
rogue_net/rogue_net/relpos_encoding.py
rogue_net/rogue_net/transformer.py

Refactor supervised.py to use [HyperState](https://github.com/cswinter/hyperstate) for managing configs.

Use HyperState for config management in supervised.py

---

entity_gym/entity_gym/environment/environment.py

Small improvement to docs for action masks. cc @vwxyzjn

Improve action mask docs

---

entity_gym/entity_gym/environment/vec_env.py
entity_gym/entity_gym/tests/test_environment.py

@vwxyzjn I believe this fixes the `pyo3_runtime.PanicException: index out of bounds: the len is 511 but the index is 511` issue.

Fix crash when action mask is sometimes None

---

configs/xprun/train.ron

This makes it possible to launch MicroRTS experiments with xprun.

Add JDK 8 to xprun build for MicroRTS

---

CONTRIBUTING.md
configs/xprun/train.ron
configs/xprun/trainbc.ron
configs/xprun/traincc.ron

I'm running into https://github.com/pytorch/pytorch/pull/57040 which should be fixed in 1.11.

Use torch 1.11.0

---

enn_ppo/enn_ppo/config.py
enn_ppo/enn_ppo/gae.py
enn_ppo/enn_ppo/rollout.py
enn_ppo/enn_ppo/train.py

Fixes memory leak/autograd issue when using dedicated value function network which is likely caused by https://github.com/pytorch/pytorch/issues/71495.

Fix memory leak

---

configs/entity-gym/rock_paper_scissors.ron
enn_ppo/enn_ppo/agent.py
enn_ppo/enn_ppo/gae.py
enn_ppo/enn_ppo/rollout.py
enn_ppo/enn_ppo/supervised.py
enn_ppo/enn_ppo/tests/test_training.py
enn_ppo/enn_ppo/train.py
enn_zoo/enn_zoo/codecraft/cc_vec_env.py
enn_zoo/enn_zoo/codecraft/codecraftnet/adapter.py
enn_zoo/enn_zoo/train.py
entity_gym/entity_gym/environment/env_list.py
entity_gym/entity_gym/environment/environment.py
entity_gym/entity_gym/environment/vec_env.py
entity_gym/entity_gym/examples/__init__.py
entity_gym/entity_gym/examples/rock_paper_scissors.py
entity_gym/entity_gym/serialization/sample_loader.py
entity_gym/entity_gym/serialization/sample_recorder.py
entity_gym/entity_gym/tests/test_environment.py
entity_gym/entity_gym/tests/test_sample_recorder.py
rogue_net/rogue_net/rogue_net.py
rogue_net/rogue_net/transformer.py

Makes it possible to show entities to the value function but not the policy.

Implement omniscent value function

---

enn_ppo/poetry.lock
enn_ppo/pyproject.toml
enn_zoo/poetry.lock
enn_zoo/pyproject.toml
poetry.lock

Fixes a bug that causes error when running CLI without specifying a config file.

Upgrade to hyperstate v0.2.11

---

configs/entity-gym/multisnake_2snakes11len.ron
poetry.lock

Resolves https://github.com/entity-neural-network/incubator/issues/51

Tuned 2snake config

---

configs/codecraft/arena_medium.ron
configs/xprun/train.ron
configs/xprun/trainbc.ron
configs/xprun/traincc.ron
enn_ppo/enn_ppo/tests/test_training.py
enn_ppo/enn_ppo/train.py
enn_ppo/poetry.lock
enn_ppo/pyproject.toml
enn_zoo/enn_zoo/codecraft/codecraftnet/adapter.py
enn_zoo/enn_zoo/codecraft/codecraftnet/codecraftnet.py
enn_zoo/enn_zoo/train.py
enn_zoo/poetry.lock
enn_zoo/pyproject.toml
poetry.lock

Allows specifying a `--checkpoint-dir` to which the training state will be persisted after every iteration. If a run is interrupted, it can be fully restored from the checkpoint directory. Also makes it possible to load policies after training has completed.

Checkpointing
