entity_gym/entity_gym/environment.py, entity_gym/entity_gym/envs/move_to_origin.py, entity_gym/entity_gym/envs/multi_armed_bandit.py, ppo/train.py
Replace the untyped `info` field of `Obs` with a typed `end_of_episode_info` struct.
Also reenable logging of total episode reward and length in PPO: https://wandb.ai/cswinter/enn-ppo/runs/3idlrvsk
=> Add `end_of_episode_info` to `Obs`

rogue_net/rogue_net/head_creator.py
This PR initializes the policy and value heads the same way openai/baselines' PPO does it. Specifically, the actor's heads are initialized with `std=0.01` and value's head `std=1.0` ([baselines/common/policies.py#L49-L63](https://github.com/openai/baselines/blob/ea25b9e8b234e6ee1bca43083f8f3cf974143998/baselines/common/policies.py#L49-L63)).
=> Layer initialization fix

enn_ppo/poetry.lock, enn_ppo/pyproject.toml, enn_zoo/poetry.lock, enn_zoo/pyproject.toml, poetry.lock, rogue_net/poetry.lock, rogue_net/pyproject.toml
This PR correctly put the main dependencies under [tool.poetry.dependencies]. Fixes #80
=> Move the main dependencies under `[tool.poetry.dependencies]`

enn_ppo/enn_ppo/train.py, enn_zoo/enn_zoo/griddly/__init__.py, entity_gym/entity_gym/envs/__init__.py
This removes the dependency of entity_gym on griddly, and initializes griddly environments lazily in enn_ppo/train.py to avoid unnecessary loading of files and log output.
=> Remove entity_gym dependency on enn_zoo and lazily initialize griddly

enn_ppo/enn_ppo/test_training.py, enn_ppo/enn_ppo/train.py, enn_ppo/pyproject.toml, entity_gym/entity_gym/environment.py, entity_gym/entity_gym/envs/cherry_pick.py, entity_gym/entity_gym/envs/pick_matching_balls.py, entity_gym/pyproject.toml, poetry.lock, rogue_net/pyproject.toml, rogue_net/rogue_net/actor.py, rogue_net/rogue_net/head_creator.py, rogue_net/rogue_net/ragged_tensor.py
This PR implements an action head for SelectEntity actions which computes a query vector for each actor and a key vector for each selectable entity (actee) using a linear projection of the embedding of the actor/actee, pads out all queries/keys to the maximum number of queries/keys in a single sample in the batch, and computes the logit of actor A selecting actee B as the dot product between the query of A and the key of B.
Fixes https://github.com/entity-neural-network/incubator/issues/19 and makes it possible to attempt https://github.com/entity-neural-network/incubator/issues/48 and https://github.com/entity-neural-network/incubator/issues/49
=> Implement SelectEntity action head

enn_ppo/enn_ppo/train.py, enn_ppo/pyproject.toml, enn_zoo/enn_zoo/griddly/wrapper.py, entity_gym/entity_gym/environment.py, entity_gym/entity_gym/envs/count.py, entity_gym/entity_gym/test_environment.py, entity_gym/pyproject.toml, mypy.ini, poetry.lock, rogue_net/rogue_net/head_creator.py
Taking inspiration from stable-baselines' vector implementation, but with some additional optimizations... the ParallelListEnv takes a `num_processes` and `num_envs` parameter. and will split the envs into equal proportions on each process.
This is better than having a process per-environment as it reduces the latency/observations ratio. (having 10 environments per process, means we can get 10 observations with only 1 send/receive from the process).
Setting `num_processes==num_envs` is equivalent to SubProcVecEnv. This has a overhead of 1 observation per send/receive.
Setting `num_processes==1` means you have no parallelization.
Setting `num_processes==8` and `num_envs=64` will give you 8 envs per-process. This has a reduced overhead of 8 observations per send/recieve.
With Griddly I can …
=> Parallel Environment Execution

rogue_net/rogue_net/transformer.py
Training with dropout results in significantly lower performance, it should be disabled by default: https://wandb.ai/entity-neural-network/enn-ppo/reports/Dropout-vs-no-dropout--VmlldzoxMzgxNzMy
=> Disable dropout

enn_ppo/enn_ppo/train.py, enn_ppo/pyproject.toml, entity_gym/pyproject.toml, poetry.lock, rogue_net/rogue_net/actor.py, rogue_net/rogue_net/head_creator.py, rogue_net/rogue_net/ragged_tensor.py, rogue_net/rogue_net/transformer.py
Completes transformer by adding a ragged multi-head self-attention operation.
The main difference to the standard attention implementation is that we additionally need to pack/pad the flattened embeddings tensor into  fixed-length sequences, and compute a mask that prevents attention from crossing example boundaries:
The heavy lifting of calculating the padded/packed arrangement is done inside the ragged-buffer package ([ragged_buffer.rs#L465-L520](https://github.com/entity-neural-network/ragged-buffer/blob/2dc76b883a4361bae3949f414c4b18cd008a6939/src/ragged_buffer.rs#L465-L520)). The current implementation pads up to the maximum sequence length, and greedily packs examples into as few sequences as possible (better heuristics that find better packings that result in less padding ought to …
=> Implement ragged attention/transformer

entity_gym/entity_gym/envs/multi_snake.py
Food can spawn at the location to which the head is going to move because we spawn the food before updating the snake.
=> Fix bug in MultiSnake food spawning

enn_ppo/enn_ppo/hypertuna.py, enn_ppo/enn_ppo/train.py, enn_ppo/pyproject.toml, entity_gym/pyproject.toml, poetry.lock, rogue_net/pyproject.toml, rogue_net/rogue_net/actor.py, rogue_net/rogue_net/translate_positions.py
Adds a `--translate` argument to `train.py` that inserts a feature transform that translates all positions to be centered at a reference entity.
Example usage: `--translate='{"reference_entity": "Vehicle", "position_features": ["x_pos", "y_pos"]}'`
This allows solving the `Minefield` task without manually implemented translation: 
https://wandb.ai/entity-neural-network/enn-ppo/reports/Translation-invariance-layer--VmlldzoxMzk2NzY0
Resolves #104
=> Implement translation invariance transform

enn_ppo/enn_ppo/simple_trace.py, enn_ppo/enn_ppo/test_training.py, enn_ppo/enn_ppo/train.py, entity_gym/entity_gym/envs/__init__.py, entity_gym/entity_gym/envs/floor_is_lava.py, rogue_net/rogue_net/actor.py, rogue_net/rogue_net/relpos_encoding.py, rogue_net/rogue_net/transformer.py, rogue_net/rogue_net/translate_positions.py
Implements a version of relative positional encoding for n-dimensional grids. Relative positional encoding with e.g. a 11 x 13 extent for an environment with a 2d grid can be enabled by passing `--relpos-encoding='{"extent": [5, 6], "position_features": ["x", "y"], "per_entity_values": true}'` to `enn_ppo/train.py`.
There are many variations and refinements of relative positional encoding. This implementation mostly follows the original formulation described in [Shaw et al (2018)](https://arxiv.org/abs/1803.02155). In particular, here is a non-exhaustive list of somewhat arbitrary design choices that we may want to revisit once we have some good benchmarks to test against:
- There are relative positional keys and values, but no queries.
- Keys and values are shared across all layers and …
=>  Implement relative positional encoding

enn_ppo/enn_ppo/hypertuna.py, enn_ppo/enn_ppo/sample_recorder.py, enn_ppo/enn_ppo/test_sample_recorder.py, enn_ppo/enn_ppo/train.py, entity_gym/entity_gym/environment.py, entity_gym/entity_gym/sample_recorder.py, entity_gym/entity_gym/test_sample_recorder.py, rogue_net/rogue_net/actor.py, rogue_net/rogue_net/head_creator.py, xprun/train.ron
- move `SampleRecorder` into the entity-gym package
- add `VecEnv` wrapper that records samples
- option to record full logits, not just probability of chosen action
- group loaded samples by episode
=> Refactor sample recorder

enn_ppo/enn_ppo/train.py
Refactors `train.py` by factoring out rollout code, and adds new `--eval-interval`, `--eval-steps` `--eval-num-envs`, and `--eval-env-kwargs` flags that allow configuring periodic evals that can use different environment configuration from rollouts.
=> [enn-ppo] Option to run evals at a fixed interval

enn_ppo/enn_ppo/train.py, enn_ppo/pyproject.toml, enn_zoo/enn_zoo/codecraft/rest_client.py, enn_zoo/enn_zoo/codecraft/vec_env.py, enn_zoo/poetry.lock, enn_zoo/pyproject.toml, entity_gym/pyproject.toml, mypy.ini, poetry.lock, rogue_net/pyproject.toml, rogue_net/rogue_net/actor.py, rogue_net/rogue_net/translate_positions.py, xprun/traincc.ron
Implements entity-gym interface for [CodeCraft](https://github.com/cswinter/codecraftgame), based on Python interface in https://github.com/cswinter/DeepCodeCraft. Currently only supports the `ALLIED_WEALTH` task where a single drone has to collect as many minerals as possible within some window.
To match the performance of the original implementation, I also added a `orientation_features` option to the `TranslatePositions` transform which rotates all other entities to align them with the direction of the reference entity, as well as an `add_dist_feature` option that adds a feature which gives the distance to the reference entity. Performance is still somewhat below my previous baselines ([W&B](https://wandb.ai/entity-neural-network/enn-ppo/reports/CodeCraft-ALLIED_WEALTH-reproduction--Vml …
=> Add CodeCraft environment

enn_ppo/enn_ppo/train.py, enn_ppo/pyproject.toml, enn_zoo/enn_zoo/codecraft/vec_env.py, enn_zoo/enn_zoo/griddly/__init__.py, enn_zoo/enn_zoo/griddly/env_descriptions/test.yaml, enn_zoo/enn_zoo/griddly/wrapper.py, entity_gym/entity_gym/environment/env_list.py, entity_gym/entity_gym/environment/environment.py, entity_gym/entity_gym/environment/parallel_env_list.py, entity_gym/entity_gym/environment/vec_env.py, entity_gym/entity_gym/serialization/sample_recorder.py, poetry.lock, pyproject.toml
Added an option for generating videos during evaluation runs:
`--eval-capture-videos`
also allowed customization of number processes used for evaluation, so we are a bit more flexible there.
`--eval-processes`
uses `writer.add_video` from tensorboard.
Videos end up in wandb looking like this and are linked to specific eval runs by global_step variable:
=> video recording for evaluation environments using tensorboard

enn_ppo/enn_ppo/train.py
Output directories configurable so things can be run on HPC clusters with temporary drives etc
In HPC settings, sometime the local disk is the worst place to store data from runs as there may be networked/fast/temporary drives that can store data for later analysis. or just ease of cleanup.
Added `--data-dir` option for this.
=> Added option to change output directory of wandb/tensorboard

entity_gym/entity_gym/environment/vec_env.py, entity_gym/entity_gym/tests/test_environment.py
The `end_of_episode_info` is keyed by the index of the environment within each batch, which causes EpisodeStats to have the wrong key and overwrite stats from other envs when merging batches. We need to add an offset to prevent collisions.
=> Fix bug in merging ObsBatches

enn_ppo/README.md, enn_ppo/enn_ppo/supervised.py, enn_ppo/enn_ppo/train.py, enn_ppo/poetry.lock, enn_ppo/pyproject.toml, enn_zoo/enn_zoo/codecraft/codecraftnet/adapter.py, enn_zoo/enn_zoo/codecraft/codecraftnet/codecraftnet.py, entity_gym/entity_gym/serialization/msgpack_ragged.py, entity_gym/entity_gym/serialization/sample_loader.py, entity_gym/entity_gym/serialization/sample_recorder.py, entity_gym/entity_gym/tests/test_sample_recorder.py, poetry.lock, rogue_net/rogue_net/actor.py, rogue_net/rogue_net/head_creator.py, rogue_net/rogue_net/tests/test_action_head.py, xprun/train.ron, xprun/trainbc.ron
Adds a new `supervised.py` script to enn-ppo which trains a model from samples recorded by another policy. Also makes various improvements to the sample recorder:
- add `--eval-capture-samples`/`--eval-capture-logits` options to record samples/logits during eval to a file
- add `--eval-on-step-0` arg to enable/disable running eval on the first step
- add `--codecraft-only-opponent` to run an eval with only a loaded eval policy against itself (this is slightly hacky, I'm planning to remove all the CodeCraft-specific options later)
- include action and observation spaces when recording samples
- fix `RaggedBufferBool` getting deserialized to `None`
- misc fixes to the `SampleRecorder` and `Trace`
Resolves https://github.com/entity-neural-network/incubator/issues/5, …
=> Behavioral cloning

entity_gym/entity_gym/environment/vec_env.py, entity_gym/entity_gym/tests/test_environment.py
Handles the case where a mask is present on some batches but not others by materializing the mask for batches where it is missing before merging as necessary.
=> Allow envs with masks only on some timesteps

enn_ppo/enn_ppo/train.py, entity_gym/entity_gym/environment/validator.py
Implements an environment wrapper, applied by default in `train.py`, which checks that the `Observation`s returned by an environment are valid. I did a quick check on the multisnake environment, and perf impact seems to be relatively low, though that could be different for environments with more entities and masks: https://wandb.ai/entity-neural-network/enn-ppo/reports/env-validate-perf-impact--VmlldzoxNjU3NTU0
Fixes https://github.com/entity-neural-network/incubator/issues/160
Fixes https://github.com/entity-neural-network/incubator/issues/181
Partial solution to https://github.com/entity-neural-network/incubator/issues/186
=> Ensure that environments return valid Obserations

.github/workflows/checks.yaml, .pre-commit-config.yaml, ARCHITECTURE.md, CONTRIBUTING.md, enn_ppo/enn_ppo/ppo.py, enn_zoo/enn_zoo/codecraft/codecraftnet/config.py, enn_zoo/enn_zoo/griddly/test_griddly_env.py, entity_gym/entity_gym/environment/environment.py, entity_gym/entity_gym/environment/parallel_env_list.py, entity_gym/entity_gym/examples/cherry_pick.py, entity_gym/entity_gym/examples/pick_matching_balls.py, entity_gym/entity_gym/examples/xor.py, poetry.lock, pyproject.toml
This PR introduces pre-commit pipelines, which include
* black: auto-format
* codespell: check word spelling
* mypy
going to add the following hooks in a follow-up PR:
* isort: automatically sort imported dependencies
* autoflake: automatically remove unused variables and unused imports
However, it does keep the tests alone because they run slow: see https://github.com/pre-commit/pre-commit-hooks/issues/291
=> Add pre-commit utilities

CONTRIBUTING.md, configs/xprun/train.ron, configs/xprun/trainbc.ron, configs/xprun/traincc.ron, enn_zoo/pyproject.toml, poetry.lock, pyproject.toml
Torch 1.11.0 is giving me segfaults, so I'm reverting back to 1.10.2. Also add setuputils==59.5.0 as a dependency to prevent installation of newer versions of setuputils which are not compatible with torch < 1.11.0.
=> Downgrade to torch==1.10.2 and setuputils==59.5.0

configs/entity-gym/multisnake_2snakes11len.ron, entity_gym/entity_gym/environment/environment.py, entity_gym/entity_gym/examples/multi_snake.py
Environment was spawning food before processing all actions, which made it possible for a food of the wrong color to spawn in the previously empty tile into which one the snakes is moving, randomly ending the game and making it impossible (or very difficult) to consistently reach the maximum score.
=> Fix bug in MultiSnake environment

enn_ppo/enn_ppo/eval.py, enn_ppo/enn_ppo/train.py
Perform a single allreduce operation over all parameters, which significantly reduces overhead and gives much better performance, especially with many data-parallel replicas. On basic tests I ran, performance matched torch DistributedDataParallel implementation.
Current implementation hits a nice sweet spot of simplicity and performance. There are more opportunities for speedups (smartly grouping parameters and running allreduce in parallel with backward pass), but exploiting these is much more involved and would probably require pulling in horovod or somesuch framework.
=> Batch allreduce ops
